name: Deploy Wiki to Pages

on:
  gollum: # Dispara quando a Wiki for editada
  workflow_dispatch: # Permite rodar manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Wiki
        run: git clone "https://github.com" wiki-content
          
      - name: Prepare Files for Jekyll
        run: |
          cp -r wiki-content/* .
          rm -rf wiki-content
          if [ -f "Home.md" ]; then cp Home.md index.md; fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
