name: Deploy Wiki to Pages

on:
  gollum: # Dispara quando a Wiki for editada
  workflow_dispatch: # Permite rodar manualmente

# Concede as permissões necessárias para o GitHub Pages funcionar
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki-content
          
      - name: Prepare Files for Jekyll
        run: |
          cp -r wiki-content/* .
          rm -rf wiki-content
          
          # Procura por qualquer variação comum de página inicial e força virar index.md
          if [ -f "Home.md" ]; then cp Home.md index.md;
          elif [ -f "home.md" ]; then cp home.md index.md;
          elif [ -f "HOME.md" ]; then cp HOME.md index.md;
          elif [ -f "main.md" ]; then cp main.md index.md;
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
